export const MaterialesData = [
  {
    id: 1,
    nombre: "Marcador",
    tipo: "suministro",
    cantidad_disponible: 200,
    estado: "nuevo",
    descripcion: "Elemento empleado para usar en tableros especiales",
    color: "negro",
    img: "../../src/assets/img/materiales/marcador-negro.png",
  },
  {
    id: 2,
    nombre: "Marcador",
    tipo: "suministro",
    cantidad_disponible: 200,
    estado: "nuevo",
    descripcion: "Elemento empleado para usar en tableros especiales",
    color: "rojo",
    img: "../../src/assets/img/materiales/marcador-rojo.png",
  },
  {
    id: 3,
    nombre: "Borrador De Tablero",
    tipo: "suministro",
    cantidad_disponible: 50,
    estado: "Nuevo",
    descripcion: "Elemento empleado para borrar en tableros especiales",
    color: "negro",
    img: "../../src/assets/img/materiales/borrador-tablero.png",
  },
  {
    id: 4,
    nombre: "Computador Corporativo",
    tipo: "Electronico",
    cantidad_disponible: 32,
    estado: "Usado",
    descripcion: "Elemento electronico para uso de los instructores ",
    color: "plateado",
    img: "../../src/assets/img/materiales/computador-portatil.png",
  },
  {
    id: 5,
    nombre: "Martillo",
    tipo: "Fisico",
    cantidad_disponible: 12,
    estado: "Usado",
    descripcion: "Elemento ",
    color: "Madera",
    img: "../../src/assets/img/materiales/martillo.png",
  },
  {
    id: 6,
    nombre: "Cable Hdmi",
    tipo: "Electronico",
    cantidad_disponible: 120,
    estado: "Nuevo",
    descripcion: "Elemento electronico para uso de transmición de imagen ",
    color: "Negro",
    img: "../../src/assets/img/materiales/hdmi.png",
  },
  {
    id: 7,
    nombre: "Proyector De Video",
    tipo: "Electronico",
    cantidad_disponible: 10,
    estado: "Usado",
    descripcion: "Elemento electronico para proyeccion de imagen ",
    color: "Negro",
    img: "../../src/assets/img/materiales/proyector.png",
  },
  {
    id: 8,
    nombre: "Destornillador",
    tipo: "Fisico",
    cantidad_disponible: 22,
    estado: "Usado",
    descripcion:
      "Herramientas diseñados para apretar o aflojar tornillos ranurados de fijación sobre materiales de madera, metálicos, plásticos etc ",
    color: "Varios",
    img: "../../src/assets/img/materiales/destornillador.png",
  }
];
